spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
    url: jdbc:mysql://119.23.236.26:3306/shiro_demo?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: honey
    password: Honey521.
  thymeleaf:
    cache: false


  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时
    timeout: 0


# Logger Config
logging:
  level:
    com.springboot.demo: debug

mybatis-plus:
  typeAliasesPackage: com.springboot.demo.sys.entity
  mapper-locations: classpath:mapper/*.xml


